r0.5.2 fix
qbic-pipelines/querynator pull request #41
Opened 2024-07-11 13:56 UTC by HomoPolyethylen

**PR Checklist**

- [x] This comment contains a description of changes (with reason)
- [ ] Referenced issue is linked
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.rst` is updated

**Description of changes**

- fixed an issue, preventing the release of v0.5.2 at pypi

**Technical details**

**Additional context**

2024-07-11 14:07 UTC, mapo9 requested changes

2024-07-11 14:07 UTC, mapo9 commented on CHANGELOG.rst
> +
you should write sth here and remove the dev

2024-07-12 09:36 UTC, HomoPolyethylen commented on CHANGELOG.rst
> +
this is not the current release but rather a template for future development. So that logs can be automatically merged by git and do not have to be performed by hand

2024-07-12 09:40 UTC, famosab commented on CHANGELOG.rst
> +
this is oriented at the way its done in nf-core tools, right? So you plan to add stuff there when you PR to dev?

2024-07-12 09:41 UTC, famosab commented on CHANGELOG.rst
> +
I would still remove it from the master branch and only keep it like that on the dev branch (otherwise it is confusing)

2024-07-12 09:57 UTC, HomoPolyethylen commented on CHANGELOG.rst
> +
yeah ok that sounds good. Is it possible to directly accept the requested changes or do I have to go through a dev PR again?

2024-07-12 10:41 UTC, HomoPolyethylen commented on CHANGELOG.rst
> +
> I would still remove it from the master branch and only keep it like that on the dev branch (otherwise it is confusing)

This is what I initially wanted, but could not think of a way to (neatly) achieve this.

2024-07-17 14:02 UTC, mapo9 approved these changes

2024-07-17 14:06 UTC, merged