Civic api
qbic-pipelines/querynator pull request #7
Opened 2023-02-06 09:37 UTC by mapo9

**PR Checklist**

- [x] This comment contains a description of changes (with reason)
- [ ] Referenced issue is linked
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] Documentation in `docs` is updated
- [ ] `CHANGELOG.rst` is updated

**Description of changes**

- added functionality to query CIViC DB
- made gzipped files queryable for CGI
- updated Docs

2023-02-06 10:43 UTC, SusiJo commented
Is the empty file `querynator/cli_tools/cli_civic.py` needed? If not, please delete it.

2023-02-06 10:49 UTC, SusiJo commented
Please check the formatting according to the linting

2023-02-06 10:51 UTC, SusiJo commented
Could you please also add a `query-api-civic` test for the cli?

2023-02-06 11:10 UTC, SusiJo commented
Concerning tests: it would be really useful to have a dummy input files for each API query which can be used for testing to see how the output looks like. Could you think of solutions like creating a folder with tiny test input and output files?

2023-02-06 11:16 UTC, SusiJo requested changes
Generally looks good! Just some minor suggestions and things that should be changed. Also please adjust the changelog.

2023-02-06 11:16 UTC, SusiJo commented on docs/usage.rst
> +The index file must be stored in the same directory as the ``vcf`` file
```suggestion
The index file must be stored in the same directory as the ``vcf`` file.

```

2023-02-06 11:52 UTC, mapo9 commented on querynator/__main__.py
> +#logger.addHandler(ch)
This is the output uncommented:

INFO:Querynator:Start
INFO:Querynator:Query the cancergenomeinterpreter (CGI)
INFO:Querynator:Unzipping input file (variants_head.vcf.gz)
INFO:Querynator:Querying REST API
INFO:Querynator:CGI Query finished
INFO:Querynator:Downloading CGI results

While commented:

2023-02-06 11:40:17,198 - Querynator - INFO - Start
INFO:Querynator:Start
2023-02-06 11:40:17,199 - Querynator - INFO - Query the cancergenomeinterpreter (CGI)
INFO:Querynator:Query the cancergenomeinterpreter (CGI)
2023-02-06 11:40:17,199 - Querynator - INFO - Unzipping input file (variants_head.vcf.gz)
INFO:Querynator:Unzipping input file (variants_head.vcf.gz)
2023-02-06 11:40:17,200 - Querynator - INFO - Querying REST API
INFO:Querynator:Querying REST API
2023-02-06 11:41:18,574 - Querynator - INFO - CGI Query finished
INFO:Querynator:CGI Query finished
2023-02-06 11:41:18,574 - Querynator - INFO - Downloading CGI results

As you see, everything is written twice, because a handler was added on top of the logger. While testing the initial querynator release, I recognized that problem and fix it as seen here, because I preferred the cleaner look:
However, if you like, I also have the fix to make the output look the following:

2023-02-06 11:49:04,362 - Querynator - INFO - Start
2023-02-06 11:49:04,363 - Querynator - INFO - Query the cancergenomeinterpreter (CGI)
2023-02-06 11:49:04,364 - Querynator - INFO - Unzipping input file (variants_head.vcf.gz)
2023-02-06 11:49:04,364 - Querynator - INFO - Querying REST API
2023-02-06 11:41:18,574 - Querynator - INFO - CGI Query finished
2023-02-06 11:41:18,574 - Querynator - INFO - Downloading CGI results

2023-02-06 12:39 UTC, mapo9 commented on querynator/__main__.py
> +    # Command to query the cancergenomeinterpreter API
This was outcommented because the appearance in the cli was not solvable from our side as far as I could see. I just tested it & click seems to have fixed the issue as the comment is not visible anymore in the cli.
Please note that these functions cannot be seen in the API-documentation by default as they are not actual functions but decatorators that return instances of a class and thus cannot be read by `modules.rst`. Was able to fix it using autofunctions in modules.rst. Unfortunately this is the best fix available so far.

2023-02-06 12:39 UTC, mapo9 commented on querynator/__main__.py
> +    # """
s.o.

2023-02-06 12:47 UTC, mapo9 commented on docs/usage.rst
> +======================================
I mean the `=` just indicates that those are subheaders instead of headers...
Don't think that can be changed.
Actually the old version was not following the [Sphinx Style-Guide](https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html)

2023-02-06 12:47 UTC, mapo9 commented on querynator/query_api/civic_api.py
> +    '''if check_if_gzipped(vcf_path):
Ah no, just forgot to remove thanks.

2023-02-06 13:20 UTC, SusiJo commented on docs/usage.rst
> +======================================
Okay thanks for adjusting it 👍

2023-02-06 13:22 UTC, SusiJo commented on querynator/__main__.py
> +#logger.addHandler(ch)
Okay, i see. So the current version is the first one?

2023-02-06 13:24 UTC, SusiJo commented
Have you run `black . && isort .`? This should fix the remaining linting errors

2023-02-06 13:37 UTC, mapo9 commented on querynator/__main__.py
> +#logger.addHandler(ch)
I switched to the last version, including the date & time

2023-02-07 10:47 UTC, SusiJo commented on docs/modules.rst
> +    :private-members:
```suggestion
    :private-members:
    
```

2023-02-07 10:52 UTC, SusiJo commented on querynator/query_api/civic_api.py
> +def check_vcf_input(vcf_path, logger):
What about `vcf.gz` input? Is that also possible?

2023-02-07 10:58 UTC, mapo9 commented on querynator/query_api/civic_api.py
> +def check_vcf_input(vcf_path, logger):
of course, pysam can read bgzipped files directly :)

2023-02-07 12:14 UTC, SusiJo commented on querynator/query_api/civic_api.py
> +def check_vcf_input(vcf_path, logger):
Perfect 👍

2023-02-07 13:54 UTC, merged