Add functionality to query CIViC Knowledgebase
qbic-pipelines/querynator pull request #8
Opened 2023-02-07 14:08 UTC by SusiJo

**PR Checklist**

- [x] This comment contains a description of changes (with reason)
- [ ] Referenced issue is linked
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] Documentation in `docs` is updated
- [x] `CHANGELOG.rst` is updated

**Description of changes**

**Technical details**

**Additional context**

2023-02-08 08:42 UTC, WackerO requested changes
LGTM, just some minor changes and I'd suggest considering some list comprehensions instead of loops for some extra performance :)

2023-02-08 08:42 UTC, WackerO commented on querynator/query_api/civic_api.py
> +    # actual search for each variant
list comp?

2023-02-08 08:58 UTC, SusiJo commented on querynator/query_api/civic_api.py
> +    coord_list = []
For efficiency this would certainly be beneficial, however, I fear that readability would suffer.

2023-02-08 09:26 UTC, mapo9 commented on querynator/__main__.py
> +    :type mutations: strs
ah no, just a typo thx!

2023-02-08 09:34 UTC, mapo9 commented on querynator/query_api/civic_api.py
> +    coord_list = []
in this case I would say that the performance of the tool will not be improved by using a list comp here as the computational bottleneck will always be querying the db and not reading in the vcf. Also, this is a very sensible function because mistakes here mean that true hits might be missed and false ones might be introduced. So, here the main focus was to ensure the readability of the code rather than trying to pack it in a l.c. considering the nested for-loops & the if-elif-else structure.

2023-02-08 09:38 UTC, mapo9 commented on querynator/query_api/civic_api.py
> +    # actual search for each variant
the bulk search actually is part of civicpy.
If you mean the for-loop below, I agree that a list comp is a considerable option, however again, I dont think that the efficiency of the tool will benefit because the `search_variants_by_coordinates` is the time-limiting step of the whole script and thus I decided to keep it simple and readable.

2023-02-08 09:52 UTC, ggabernet approved these changes
Looks good to me

2023-02-08 09:52 UTC, ggabernet commented on querynator/query_api/civic_api.py
> +    coord_list = []
yes I agree that for these many conditions, list comprehension would make the code not readable

2023-02-08 09:52 UTC, ggabernet commented on requirements-dev.txt
> +pandas==1.4.4
why is `requirements_dev` and `requirements` needed?

2023-02-09 06:30 UTC, SusiJo commented on requirements-dev.txt
> +pandas==1.4.4
The `requirements_dev` is just for developing so that one automatically has all necessary packages also for linting locally.

2023-02-10 08:30 UTC, WackerO approved these changes

2023-02-10 08:42 UTC, merged